### ISSUE TITLE
No Raw Dataset

### ISSUE THREAD

**Issue by shadowfall09** [w11wo/GenUP#1]
Hi, could you upload the raw dataset？ Thanks

**Comment by w11wo** [comment]
Hi @shadowfall09. I've made a major update on the README for dataset preparation steps. Otherwise, you can also find our processed version of LLM4POI dataset [here](https://huggingface.co/datasets/w11wo/LLM4POI). Hope this helps.

**Comment by shadowfall09** [comment]
Thanks for help!
